name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check clean notebook
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
